apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prometheus-clusterissuer
  namespace: kube-prometheus-stack
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: suonvicheak991@gmail.com
    privateKeySecretRef:
      name: prometheus-key
    solvers:
    - http01:
        ingress:
          class: nginx
