apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector: 
    matchLabels:
      tier: nginx-app
  template:
    metadata:
      labels:
        tier: nginx-app
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: nginx-cont
          image: registry.cheakautomate.online/nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30005
# Description : first of all, you have to deploy a private registry