apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: nginx-testing
  name: my-nginx-replicaset
  labels:
    app: my-nginx-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-lbl
  template:
    metadata:
      labels:
        app: my-nginx-lbl
    spec:
      containers:
        - name: my-nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80