apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-nginx-lbl
  name: my-nginx-pod
  namespace: nginx-testing
spec: 
  containers:
    - name: my-nginx-cont
      image: nginx:latest
      ports: 
        - containerPort: 80