apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-reactjs-lbl
  name: my-reactjs-pod
  namespace: reactjs-testing
spec: 
  containers:
    - name: my-reactjs-cont
      image: vicheak/reactjs-app:latest
      ports: 
        - containerPort: 80