apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      nodeSelector:
        task: worker
      containers:
      - image: mysql
        name: mysql-cont
        ports:
        - containerPort: 3306
        envFrom: 
          - secretRef: 
              name: mysql-secret
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        hostPath:
          path: /home/vicheak/mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql-app
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: NodePort