apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: wordpress-deploy
spec:
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      nodeSelector:
        task: worker
      containers:
      - image: mysql
        name: mysql-cont
        ports:
        - containerPort: 3306
        envFrom: 
          - secretRef:
              name: mysql-secret
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      # securityContext:
      #   fsGroup: 0
      # volumes:
      #   - name: mysql-storage
      #     persistentVolumeClaim:
      #       claimName: mysql-pvc
      volumes:
        - name: mysql-storage
          hostPath:
            path: /home/vicheak/mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: wordpress-deploy
spec:
  selector:
    app: mysql-app
  ports:
    - port: 3306
      protocol: TCP
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-ingress
  namespace: wordpress-deploy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingressClassName: "nginx"
spec:
  tls:
  - hosts:
    - cms.cheakautomate.online
    secretName: mysql-ingress-tls
  rules:
  - host: cms.cheakautomate.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysql-svc
            port:
              number: 3306