apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  selector:
    matchLabels:
      app: wordpress-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      nodeSelector:
        task: worker
      containers:
      - image: wordpress
        name: wordpress-cont
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef: 
              name: wordpress-config
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        hostPath:
          path: /home/vicheak/wordpress-data
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort