apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  namespace: wordpress-deploy
spec:
  selector:
    matchLabels:
      app: wordpress-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      nodeSelector:
        task: cms-service
      containers:
      - image: wordpress
        name: wordpress-cont
        envFrom:
          - configMapRef: 
              name: wordpress-config
        ports:
          - containerPort: 80
        volumeMounts:
          - name: wordpress-storage
            mountPath: /var/www/html
      volumes:
        - name: wordpress-storage
          hostPath:
            path: /home/vicheak/wordpress-data
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: wordpress-deploy
spec:
  selector:
    app: wordpress-app
  ports:
    - port: 80
      protocol: TCP
  type: NodePort