apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-app-lbl
  ports:
  - name: nginx-app-port
    port: 80 # internal or clusterIP port
    targetPort: 80 # must match with the container port