apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  type: NodePort
  selector:
    app: react-deploy-lbl
  ports:
  - name: react-app-port
    port: 8080
    targetPort: 80
    nodePort: 30005