apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-deploy
  template:
    metadata:
      labels:
        app: react-deploy
    spec:
      containers:
      - name: react-cont
        image: vicheak/reactjs-app:latest
        resources: 
          requests: 
            cpu: 250m 
            memory: "512Mi"
          limits:
            cpu: 500m 
            memory: "1Gi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  type: NodePort
  selector:
    app: react-deploy
  ports:
  - name: react-app-port
    port: 8080
    targetPort: 80
    nodePort: 30005