apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-deployment-lbl
  template:sd
    metadata:
      labels:
        app: my-nginx-deployment-lbl
    spec:
      containers:
      - name: my-nginx-cont
        image: nginx:latest
        ports:
        - containerPort: 80
      nodeSelector:
        hardware: high-spec
