apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-deploy-lbl
  template:
    metadata:
      labels:
        app: react-deploy-lbl
    spec:
      containers:
        - name: react-cont
          image: vicheak/reactjs-app:latest
          ports:
            - containerPort: 80