apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: spring-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sharing
  nfs:
    server: 167.172.70.166
    path: /opt/nfs/data
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: spring-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sharing
