apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-cont
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: config-volume
              mountPath: /usr/share/nginx
      volumes:
        - name: config-volume
          configMap: 
            name: index-configmap
            items: 
              - key: index.html
                path: html/index.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - port: 80
      nodePort: 30005