apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres-cont
          image: postgres
          ports:
            - containerPort: 5432
          envFrom: 
            - secretRef: 
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: NodePort
  selector:
    app: postgres-app
  ports:
    - port: 80
      targetPort: 5432
      nodePort: 30005