apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-deployment
  namespace: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
        - name: core-api
          image: vicheak/core-api:prod-1.0.8
          ports:
            - containerPort: 8080
