apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-deployment
  namespace: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
        - name: core-api
          image: vicheak/core-api:prod-1.0.7
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: core-api-service
  namespace: myapp
spec:
  selector:
    app: core-api
  ports:
    - protocol: TCP
      nodePort: 32300
      targetPort: 8080
  type: NodePort